'use strict';
const net=require('net'),fs=require('fs');
const CFG='/data/shackclock-settings.json', OUT='/data/dx-spots.json';
let socket=null, buffer='', spots=[], currentKey='', connected=false, reconnectTimer=null;
function env(k,d=''){return process.env[k]!==undefined?process.env[k]:d;}
function cfg(){let c={};try{c=JSON.parse(fs.readFileSync(CFG,'utf8'));}catch(_){};const v=(k,d='')=>Object.prototype.hasOwnProperty.call(c,k)?c[k]:env(k,d);return {enabled:String(v('DX_CLUSTER_ENABLED','true')).toLowerCase()!=='false',host:String(v('DX_CLUSTER_HOST','w3lpl.net')),port:Number(v('DX_CLUSTER_PORT','7373'))||7373,call:String(v('DX_CLUSTER_CALL',v('STATION_CALL','N0CALL'))).toUpperCase(),maxAge:Number(v('DX_CLUSTER_MAX_AGE_MIN','20'))||20};}
function mode(freq,comment){const c=String(comment||'').toUpperCase();for(const m of ['FT8','FT4','RTTY','PSK','CW','SSB','USB','LSB','FM','AM'])if(c.includes(m))return m;const f=Number(freq);if(!Number.isFinite(f))return '';if((f>=14070&&f<=14080)||(f>=7070&&f<=7080)||(f>=21070&&f<=21080)||(f>=28070&&f<=28090))return 'DIGI';return '';}
function parse(line){const m=line.match(/^DX de\s+([^:]+):\s*([0-9.]+)\s+([^\s]+)\s*(.*)$/i);if(!m)return null;let rest=m[4].trim(), utc='';const tm=rest.match(/\b(\d{4}Z)\b/);if(tm){utc=tm[1];rest=rest.replace(tm[0],'').trim();}const gridm=rest.match(/\b([A-R]{2}\d{2}[A-X]{0,2})\b/i);return {spotter:m[1].trim(),frequency:Number(m[2]),call:m[3].trim().toUpperCase(),comment:rest,mode:mode(Number(m[2]),rest),utc,grid:gridm?gridm[1].toUpperCase():'',receivedAt:Date.now()};}
function save(extra={}){const c=cfg(),cut=Date.now()-c.maxAge*60000;spots=spots.filter(s=>s.receivedAt>=cut).slice(0,600);const data={connected,host:c.host,port:c.port,call:c.call,updatedAt:Date.now(),spotCount:spots.length,spots,...extra};try{fs.writeFileSync(OUT,JSON.stringify(data));}catch(e){console.error('[DX] write',e.message);}}
function disconnect(){if(socket){try{socket.destroy();}catch(_){}socket=null;}connected=false;}
function connect(){const c=cfg(),key=JSON.stringify(c);currentKey=key;if(!c.enabled){disconnect();save({disabled:true});return;}disconnect();console.log(`[DX] connecting ${c.host}:${c.port} as ${c.call}`);socket=net.createConnection({host:c.host,port:c.port});socket.setKeepAlive(true,30000);socket.setTimeout(180000);socket.on('connect',()=>{connected=true;save();setTimeout(()=>{if(socket&&!socket.destroyed){socket.write(c.call+'\r\n');}},700);});socket.on('data',buf=>{buffer+=buf.toString('utf8');let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i).replace(/\r/g,'').trim();buffer=buffer.slice(i+1);if(/login|call/i.test(line)&&line.length<120&&socket&&!socket.destroyed)socket.write(c.call+'\r\n');const s=parse(line);if(s){spots.unshift(s);save();}}});const fail=e=>{if(e)console.error('[DX]',e.message||e);connected=false;save({lastError:e&&e.message?e.message:String(e||'disconnected')});clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,10000);};socket.on('error',fail);socket.on('close',()=>fail('closed'));socket.on('timeout',()=>{try{socket.destroy();}catch(_){}});}
setInterval(()=>{const c=cfg(),key=JSON.stringify(c);if(key!==currentKey)connect();else save();},5000);
connect();
