'use strict';
const net=require('net'),fs=require('fs'),http=require('http'),https=require('https');
const CFG='/data/shackclock-settings.json', OUT='/data/dx-spots.json';
let socket=null,buffer='',spots=[],currentKey='',connected=false,reconnectTimer=null,summitTimer=null,generation=0;
function env(k,d=''){return process.env[k]!==undefined?process.env[k]:d;}
function cfg(){let c={};try{c=JSON.parse(fs.readFileSync(CFG,'utf8'));}catch(_){};const v=(k,d='')=>Object.prototype.hasOwnProperty.call(c,k)?c[k]:env(k,d);const source=String(v('DX_SOURCE','cluster')).toLowerCase()==='dxsummit'?'dxsummit':'cluster';const legacyPrimary='https://www.dxsummit.fi/api/v1/spots?content_type=csv&limit=100',legacyFallback='https://www.dxsummit.fi/text/dx100.html';let summitUrl=String(v('DX_SUMMIT_URL','http://www.dxsummit.fi/api/v1/spots?content_type=csv&limit=100')),summitFallbackUrl=String(v('DX_SUMMIT_FALLBACK_URL','http://www.dxsummit.fi/text/dx100.html'));if(summitUrl===legacyPrimary)summitUrl='http://www.dxsummit.fi/api/v1/spots?content_type=csv&limit=100';if(summitFallbackUrl===legacyFallback)summitFallbackUrl='http://www.dxsummit.fi/text/dx100.html';return{enabled:String(v('DX_CLUSTER_ENABLED','true')).toLowerCase()!=='false',source,host:String(v('DX_CLUSTER_HOST','w3lpl.net')),port:Number(v('DX_CLUSTER_PORT','7373'))||7373,call:String(v('DX_CLUSTER_CALL',v('STATION_CALL','N0CALL'))).toUpperCase(),maxAge:Number(v('DX_CLUSTER_MAX_AGE_MIN','20'))||20,summitUrl,summitFallbackUrl,summitRefreshSec:Math.max(60,Number(v('DX_SUMMIT_REFRESH_SEC','60'))||60)};}
function mode(freq,comment){const c=String(comment||'').toUpperCase();for(const m of ['FT8','FT4','RTTY','PSK','CW','SSB','USB','LSB','FM','AM','WSPR','Q65','JT65'])if(c.includes(m))return m;const f=Number(freq);if(!Number.isFinite(f))return '';if((f>=14070&&f<=14080)||(f>=7070&&f<=7080)||(f>=21070&&f<=21080)||(f>=28070&&f<=28090)||(f>=50000&&f<=50350))return'DIGI';return'';}
function parseClusterLine(line){const m=String(line||'').match(/^DX de\s+([^:]+):\s*([0-9.]+)\s+([^\s]+)\s*(.*)$/i);if(!m)return null;let rest=m[4].trim(),utc='';const tm=rest.match(/\b(\d{4}Z)\b/);if(tm){utc=tm[1];rest=rest.replace(tm[0],'').trim();}const gridm=rest.match(/\b([A-R]{2}\d{2}[A-X]{0,2})\b/i);return{spotter:m[1].trim(),frequency:Number(m[2]),call:m[3].trim().toUpperCase(),comment:rest,mode:mode(Number(m[2]),rest),utc,grid:gridm?gridm[1].toUpperCase():'',receivedAt:Date.now(),source:'cluster'};}
function decodeHtml(s=''){return String(s).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&#x2F;/gi,'/');}
function stripHtml(s=''){return decodeHtml(String(s).replace(/<br\s*\/?>/gi,' ').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim());}
function parseCsvRows(text=''){const rows=[];let row=[],field='',quoted=false,s=String(text);for(let i=0;i<s.length;i++){const ch=s[i];if(quoted){if(ch==='"'&&s[i+1]==='"'){field+='"';i++;}else if(ch==='"')quoted=false;else field+=ch;}else{if(ch==='"')quoted=true;else if(ch===','){row.push(field.trim());field='';}else if(ch==='\n'){row.push(field.trim());if(row.some(Boolean))rows.push(row);row=[];field='';}else if(ch!=='\r')field+=ch;}}row.push(field.trim());if(row.some(Boolean))rows.push(row);return rows;}
function keyName(s=''){return String(s).toLowerCase().replace(/[^a-z0-9]/g,'');}
function parseSpotTime(v=''){const raw=String(v||'').trim();if(!raw)return Date.now();let t=Date.parse(raw);if(Number.isFinite(t))return t;const m=raw.match(/(\d{1,2}):(\d{2})\s+(\d{1,2})\s+([A-Za-z]{3})/);if(m){const mons={jan:0,feb:1,mar:2,apr:3,may:4,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11},mon=mons[m[4].toLowerCase()];if(mon!==undefined){let d=Date.UTC(new Date().getUTCFullYear(),mon,Number(m[3]),Number(m[1]),Number(m[2]));if(d>Date.now()+2*86400000)d=Date.UTC(new Date().getUTCFullYear()-1,mon,Number(m[3]),Number(m[1]),Number(m[2]));return d;}}const z=raw.match(/\b(\d{2})(\d{2})Z\b/i);if(z){const now=new Date();let d=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate(),Number(z[1]),Number(z[2]));if(d>Date.now()+3600000)d-=86400000;return d;}return Date.now();}
function normalizeWebSpot(input={}){const get=(...names)=>{for(const n of names){if(input[n]!==undefined&&input[n]!==null&&String(input[n]).trim()!=='')return input[n];const nk=keyName(n);for(const[k,v]of Object.entries(input))if(keyName(k)===nk&&v!==undefined&&v!==null&&String(v).trim()!=='')return v;}return'';};const spotter=String(get('spotter','de','reporter','sourceCall','source')).trim(),call=String(get('dx','call','callsign','dxCall','station')).trim().toUpperCase();let frequency=Number(String(get('freq','frequency','qrg','khz')).replace(/[^\d.]/g,''));if(!Number.isFinite(frequency)||!call)return null;if(frequency>1e6)frequency/=1000;const comment=String(get('info','comment','comments','message','notes')).trim(),time=String(get('time','utc','datetime','timestamp','date')).trim(),gridm=comment.match(/\b([A-R]{2}\d{2}[A-X]{0,2})\b/i);return{spotter,frequency,call,comment,mode:mode(frequency,comment),utc:time,grid:gridm?gridm[1].toUpperCase():'',country:String(get('country','dxCountry')).trim(),receivedAt:parseSpotTime(time),source:'dxsummit'};}
function parseDxSummitJson(text=''){try{const d=JSON.parse(text),rows=Array.isArray(d)?d:(Array.isArray(d?.spots)?d.spots:(Array.isArray(d?.data)?d.data:[]));return rows.map(normalizeWebSpot).filter(Boolean);}catch(_){return[];}}
function parseDxSummitCsv(text=''){const rows=parseCsvRows(text);if(!rows.length)return[];const h=rows[0].map(keyName),known=h.some(x=>['spotter','freq','frequency','dx','time','info','country'].includes(x)),data=known?rows.slice(1):rows,out=[];for(const r of data){let o={};if(known)h.forEach((k,i)=>{if(k)o[k]=r[i]??'';});else if(r.length>=3)o={spotter:r[0],freq:r[1],dx:r[2],time:r[3]||'',info:r[4]||'',country:r[5]||''};const sp=normalizeWebSpot(o);if(sp)out.push(sp);}return out;}
function parseDxSummitHtml(text=''){const out=[],rows=[...String(text).matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)];for(const m of rows){const cells=[...m[1].matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>stripHtml(x[1]));if(cells.length<3)continue;const sp=normalizeWebSpot({spotter:cells[0],freq:cells[1],dx:cells[2],time:cells[3]||'',info:cells[4]||'',country:cells[5]||''});if(sp)out.push(sp);}return out;}
function parseDxSummitText(text=''){const out=[];for(const raw of String(text).split(/\r?\n/)){const line=stripHtml(raw);if(!line)continue;const cl=parseClusterLine(line);if(cl){cl.source='dxsummit';out.push(cl);continue;}const m=line.match(/^(\S+)\s+([0-9.]+)\s+(\S+)\s+(\d{1,2}:\d{2}(?:\s+\d{1,2}\s+[A-Za-z]{3})?)\s*(.*)$/);if(m){const sp=normalizeWebSpot({spotter:m[1],freq:m[2],dx:m[3],time:m[4],info:m[5]});if(sp)out.push(sp);}}return out;}
function dedupe(list=[]){const seen=new Set(),out=[];for(const sp of list){const k=[sp.call,Number(sp.frequency).toFixed(2),sp.spotter,sp.utc||''].join('|').toUpperCase();if(seen.has(k))continue;seen.add(k);out.push(sp);}out.sort((a,b)=>(b.receivedAt||0)-(a.receivedAt||0));return out;}
function parseDxSummitBody(text='',contentType=''){const body=String(text||'').trim();if(!body)return[];let out=[];if(/json/i.test(contentType)||/^[\[{]/.test(body))out=parseDxSummitJson(body);if(!out.length&&(/csv/i.test(contentType)||body.includes(',')))out=parseDxSummitCsv(body);if(!out.length&&/<t(?:able|r|d|h)\b/i.test(body))out=parseDxSummitHtml(body);if(!out.length)out=parseDxSummitText(body);return dedupe(out);}
function save(extra={}){const c=cfg(),cut=Date.now()-c.maxAge*60000;spots=spots.filter(sp=>!sp.receivedAt||sp.receivedAt>=cut).slice(0,600);const data={connected,source:c.source,sourceLabel:c.source==='dxsummit'?'DX Summit':`${c.host}:${c.port}`,host:c.source==='dxsummit'?'DX Summit':c.host,port:c.source==='dxsummit'?null:c.port,call:c.call,updatedAt:Date.now(),spotCount:spots.length,spots,...extra};try{fs.writeFileSync(OUT,JSON.stringify(data,null,2));}catch(e){console.error('[DX] write',e.message);}}
function stopAll(){generation++;clearTimeout(reconnectTimer);reconnectTimer=null;clearInterval(summitTimer);summitTimer=null;if(socket){try{socket.destroy();}catch(_){}socket=null;}connected=false;}
function connectCluster(c,gen){console.log(`[DX] source=cluster · connecting ${c.host}:${c.port} as ${c.call}`);socket=net.createConnection({host:c.host,port:c.port});socket.setKeepAlive(true,30000);socket.setTimeout(180000);socket.on('connect',()=>{if(gen!==generation)return;connected=true;save({lastError:''});setTimeout(()=>{if(gen===generation&&socket&&!socket.destroyed)socket.write(c.call+'\r\n');},700);});socket.on('data',buf=>{if(gen!==generation)return;buffer+=buf.toString('utf8');let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i).replace(/\r/g,'').trim();buffer=buffer.slice(i+1);if(/login|call/i.test(line)&&line.length<120&&socket&&!socket.destroyed)socket.write(c.call+'\r\n');const sp=parseClusterLine(line);if(sp){spots.unshift(sp);save();}}});const fail=e=>{if(gen!==generation)return;connected=false;const msg=e&&e.message?e.message:String(e||'disconnected');save({lastError:msg});clearTimeout(reconnectTimer);reconnectTimer=setTimeout(activate,10000);};socket.on('error',fail);socket.on('close',()=>fail('closed'));socket.on('timeout',()=>{try{socket.destroy();}catch(_){}});}
function fetchFeed(url,timeout=20000,redirects=0){return new Promise((resolve,reject)=>{let u;try{u=new URL(url);}catch(e){reject(new Error(`invalid URL: ${e.message}`));return;}const client=u.protocol==='https:'?https:(u.protocol==='http:'?http:null);if(!client){reject(new Error(`unsupported protocol: ${u.protocol}`));return;}const req=client.get({hostname:u.hostname,port:u.port||(u.protocol==='https:'?443:80),path:`${u.pathname}${u.search}`,family:4,headers:{'User-Agent':'ShackClock/1.1.1','Accept':'text/csv,text/plain,text/html,application/json;q=0.9,*/*;q=0.2','Cache-Control':'no-cache'}},res=>{const status=Number(res.statusCode||0);const location=res.headers.location;if(status>=300&&status<400&&location){res.resume();if(redirects>=5){reject(new Error('too many redirects'));return;}let next;try{next=new URL(location,u).toString();}catch(e){reject(new Error(`bad redirect: ${e.message}`));return;}fetchFeed(next,timeout,redirects+1).then(resolve,reject);return;}let body='';res.setEncoding('utf8');res.on('data',chunk=>{body+=chunk;});res.on('end',()=>{if(status<200||status>=300){reject(new Error(`HTTP ${status} ${res.statusMessage||''}`.trim()));return;}resolve({text:body,contentType:res.headers['content-type']||'',url:u.toString()});});});req.setTimeout(timeout,()=>req.destroy(new Error(`ETIMEDOUT after ${timeout}ms`)));req.on('error',e=>{const code=e&&e.code?`${e.code}: `:'';reject(new Error(`${code}${e.message||String(e)}`));});});}
async function pollDxSummit(c,gen){const urls=[c.summitUrl,c.summitFallbackUrl].filter(Boolean),errors=[];for(const url of urls){try{const res=await fetchFeed(url),parsed=parseDxSummitBody(res.text,res.contentType);if(!parsed.length)throw new Error('feed returned no parseable spots');if(gen!==generation)return;spots=parsed;connected=true;save({sourceUrl:res.url,lastError:'',fetchedAt:Date.now()});console.log(`[DX] DX Summit: ${spots.length} spots from ${res.url}`);return;}catch(e){errors.push(`${url}: ${e.message}`);}}if(gen!==generation)return;connected=false;const lastError=errors.join(' | ');save({lastError});console.warn(`[DX] DX Summit poll failed: ${lastError}`);}
function startDxSummit(c,gen){console.log(`[DX] source=dxsummit · refresh=${c.summitRefreshSec}s`);pollDxSummit(c,gen);summitTimer=setInterval(()=>pollDxSummit(cfg(),gen),c.summitRefreshSec*1000);}
function activate(){stopAll();const c=cfg();currentKey=JSON.stringify(c);const gen=generation;if(!c.enabled){save({disabled:true,lastError:''});console.log('[DX] feed disabled');return;}if(c.source==='dxsummit')startDxSummit(c,gen);else connectCluster(c,gen);}
function main(){setInterval(()=>{const c=cfg(),key=JSON.stringify(c);if(key!==currentKey)activate();else if(c.source==='cluster')save();},5000);activate();}
module.exports={parseClusterLine,parseDxSummitBody,parseDxSummitCsv,parseDxSummitHtml,normalizeWebSpot,mode};
if(require.main===module)main();
